// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Max_Pooling_10x10,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.664000,HLS_SYN_LAT=53,HLS_SYN_TPT=none,HLS_SYN_MEM=22,HLS_SYN_DSP=0,HLS_SYN_FF=1773,HLS_SYN_LUT=2944,HLS_VERSION=2019_2}" *)

module Max_Pooling_10x10 (
        ap_clk,
        ap_rst_n,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_pp0_stage0 = 12'd2;
parameter    ap_ST_fsm_pp0_stage3 = 12'd4;
parameter    ap_ST_fsm_pp0_stage1 = 12'd8;
parameter    ap_ST_fsm_pp0_stage2 = 12'd16;
parameter    ap_ST_fsm_pp0_stage4 = 12'd32;
parameter    ap_ST_fsm_pp0_stage5 = 12'd64;
parameter    ap_ST_fsm_pp0_stage6 = 12'd128;
parameter    ap_ST_fsm_pp0_stage7 = 12'd256;
parameter    ap_ST_fsm_pp0_stage8 = 12'd512;
parameter    ap_ST_fsm_pp0_stage9 = 12'd1024;
parameter    ap_ST_fsm_state14 = 12'd2048;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 10;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;

 reg    ap_rst_n_inv;
reg   [3:0] ifmap_0_address0;
reg    ifmap_0_ce0;
wire   [31:0] ifmap_0_q0;
reg   [3:0] ifmap_1_address0;
reg    ifmap_1_ce0;
wire   [31:0] ifmap_1_q0;
reg   [3:0] ifmap_2_address0;
reg    ifmap_2_ce0;
wire   [31:0] ifmap_2_q0;
reg   [3:0] ifmap_3_address0;
reg    ifmap_3_ce0;
wire   [31:0] ifmap_3_q0;
reg   [3:0] ifmap_4_address0;
reg    ifmap_4_ce0;
wire   [31:0] ifmap_4_q0;
reg   [3:0] ifmap_5_address0;
reg    ifmap_5_ce0;
wire   [31:0] ifmap_5_q0;
reg   [3:0] ifmap_6_address0;
reg    ifmap_6_ce0;
wire   [31:0] ifmap_6_q0;
reg   [3:0] ifmap_7_address0;
reg    ifmap_7_ce0;
wire   [31:0] ifmap_7_q0;
reg   [3:0] ifmap_8_address0;
reg    ifmap_8_ce0;
wire   [31:0] ifmap_8_q0;
reg   [3:0] ifmap_9_address0;
reg    ifmap_9_ce0;
wire   [31:0] ifmap_9_q0;
reg   [4:0] result_address0;
reg    result_ce0;
reg    result_we0;
reg   [31:0] result_d0;
reg   [4:0] indvars_iv_reg_1003;
reg   [4:0] indvars_iv_reg_1003_pp0_iter1_reg;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state12_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] i_0_reg_1015;
reg   [4:0] idx_0_reg_1027;
reg   [31:0] phi_ln15_reg_1090;
reg   [31:0] phi_ln15_1_reg_1141;
reg   [31:0] phi_ln15_2_reg_1207;
reg   [31:0] phi_ln15_3_reg_1273;
reg   [31:0] phi_ln15_4_reg_1339;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln10_fu_1370_p2;
reg   [0:0] icmp_ln10_reg_2147;
reg   [0:0] icmp_ln10_reg_2147_pp0_iter1_reg;
wire   [3:0] or_ln15_fu_1376_p2;
reg   [3:0] or_ln15_reg_2151;
wire   [5:0] zext_ln10_fu_1382_p1;
reg   [5:0] zext_ln10_reg_2155;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state3_pp0_stage3_iter0;
wire    ap_block_pp0_stage3_11001;
wire   [4:0] add_ln17_fu_1413_p2;
reg   [4:0] add_ln17_reg_2162;
reg    ap_enable_reg_pp0_iter0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state4_pp0_stage1_iter0;
wire    ap_block_state13_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
wire   [31:0] select_ln14_fu_1430_p3;
reg   [31:0] select_ln14_reg_2267;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state5_pp0_stage2_iter0;
wire    ap_block_pp0_stage2_11001;
wire   [31:0] select_ln14_1_fu_1444_p3;
reg   [31:0] select_ln14_1_reg_2298;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state6_pp0_stage4_iter0;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state7_pp0_stage5_iter0;
wire    ap_block_pp0_stage5_11001;
wire   [31:0] select_ln14_2_fu_1489_p3;
reg   [31:0] select_ln14_2_reg_2379;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state8_pp0_stage6_iter0;
wire    ap_block_pp0_stage6_11001;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state9_pp0_stage7_iter0;
wire    ap_block_pp0_stage7_11001;
wire   [31:0] select_ln14_3_fu_1540_p3;
reg   [31:0] select_ln14_3_reg_2460;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_state10_pp0_stage8_iter0;
wire    ap_block_pp0_stage8_11001;
wire   [5:0] add_ln17_3_fu_1580_p2;
reg   [5:0] add_ln17_3_reg_2491;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_state11_pp0_stage9_iter0;
wire    ap_block_pp0_stage9_11001;
wire   [3:0] i_fu_1590_p2;
reg   [3:0] i_reg_2546;
wire   [4:0] add_ln10_fu_1596_p2;
reg   [4:0] add_ln10_reg_2551;
wire   [31:0] select_ln14_4_fu_1608_p3;
reg   [31:0] select_ln14_4_reg_2556;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage0;
reg   [3:0] ap_phi_mux_i_0_phi_fu_1019_p4;
reg   [31:0] ap_phi_reg_pp0_iter0_phi_ln16_reg_1040;
reg   [31:0] ap_phi_reg_pp0_iter0_phi_ln13_reg_1055;
reg   [31:0] ap_phi_mux_phi_ln14_phi_fu_1073_p10;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln14_reg_1070;
reg   [31:0] ap_phi_reg_pp0_iter0_phi_ln15_reg_1090;
reg   [31:0] ap_phi_reg_pp0_iter0_phi_ln13_1_reg_1106;
reg   [31:0] ap_phi_mux_phi_ln14_1_phi_fu_1124_p10;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln14_1_reg_1121;
reg   [31:0] ap_phi_reg_pp0_iter0_phi_ln15_1_reg_1141;
reg   [31:0] ap_phi_reg_pp0_iter0_phi_ln16_1_reg_1157;
reg   [31:0] ap_phi_reg_pp0_iter0_phi_ln13_2_reg_1172;
reg   [31:0] ap_phi_mux_phi_ln14_2_phi_fu_1190_p10;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln14_2_reg_1187;
reg   [31:0] ap_phi_reg_pp0_iter0_phi_ln15_2_reg_1207;
reg   [31:0] ap_phi_reg_pp0_iter0_phi_ln16_2_reg_1223;
reg   [31:0] ap_phi_reg_pp0_iter0_phi_ln13_3_reg_1238;
reg   [31:0] ap_phi_mux_phi_ln14_3_phi_fu_1256_p10;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln14_3_reg_1253;
reg   [31:0] ap_phi_reg_pp0_iter0_phi_ln15_3_reg_1273;
reg   [31:0] ap_phi_reg_pp0_iter0_phi_ln16_3_reg_1289;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln13_4_reg_1304;
reg   [31:0] ap_phi_reg_pp0_iter1_phi_ln13_4_reg_1304;
reg   [31:0] ap_phi_mux_phi_ln14_4_phi_fu_1322_p10;
wire   [31:0] ap_phi_reg_pp0_iter1_phi_ln14_4_reg_1319;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln15_4_reg_1339;
reg   [31:0] ap_phi_reg_pp0_iter1_phi_ln15_4_reg_1339;
wire   [31:0] ap_phi_reg_pp0_iter0_phi_ln16_4_reg_1355;
reg   [31:0] ap_phi_reg_pp0_iter1_phi_ln16_4_reg_1355;
wire   [63:0] zext_ln17_fu_1419_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln17_1_fu_1479_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln17_2_fu_1529_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln17_3_fu_1585_p1;
wire    ap_block_pp0_stage9;
wire   [63:0] zext_ln17_4_fu_1643_p1;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage4;
wire    ap_block_pp0_stage6;
wire    ap_block_pp0_stage8;
wire   [31:0] select_ln16_fu_1404_p3;
wire   [31:0] select_ln16_1_fu_1470_p3;
wire   [31:0] select_ln16_2_fu_1520_p3;
wire   [31:0] select_ln16_3_fu_1571_p3;
wire   [31:0] select_ln16_4_fu_1634_p3;
wire   [0:0] icmp_ln15_fu_1386_p2;
wire   [31:0] select_ln15_fu_1391_p3;
wire   [0:0] icmp_ln16_fu_1398_p2;
wire   [0:0] icmp_ln14_fu_1424_p2;
wire   [0:0] icmp_ln14_1_fu_1438_p2;
wire   [0:0] icmp_ln15_1_fu_1452_p2;
wire   [31:0] select_ln15_1_fu_1457_p3;
wire   [0:0] icmp_ln16_1_fu_1464_p2;
wire   [0:0] icmp_ln14_2_fu_1483_p2;
wire   [0:0] icmp_ln15_2_fu_1502_p2;
wire   [31:0] select_ln15_2_fu_1507_p3;
wire   [0:0] icmp_ln16_2_fu_1514_p2;
wire   [5:0] add_ln17_1_fu_1497_p2;
wire   [0:0] icmp_ln14_3_fu_1534_p2;
wire   [0:0] icmp_ln15_3_fu_1553_p2;
wire   [31:0] select_ln15_3_fu_1558_p3;
wire   [0:0] icmp_ln16_3_fu_1565_p2;
wire   [5:0] add_ln17_2_fu_1548_p2;
wire   [0:0] icmp_ln14_4_fu_1602_p2;
wire   [0:0] icmp_ln15_4_fu_1616_p2;
wire   [31:0] select_ln15_4_fu_1621_p3;
wire   [0:0] icmp_ln16_4_fu_1628_p2;
reg   [11:0] ap_NS_fsm;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_1155;
reg    ap_condition_896;
reg    ap_condition_898;
reg    ap_condition_902;
reg    ap_condition_1168;
reg    ap_condition_1173;
reg    ap_condition_1049;
reg    ap_condition_1057;
reg    ap_condition_1066;
reg    ap_condition_1046;
reg    ap_condition_438;
reg    ap_condition_679;
reg    ap_condition_468;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

Max_Pooling_10x10_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
Max_Pooling_10x10_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ifmap_0_address0(ifmap_0_address0),
    .ifmap_0_ce0(ifmap_0_ce0),
    .ifmap_0_q0(ifmap_0_q0),
    .ifmap_1_address0(ifmap_1_address0),
    .ifmap_1_ce0(ifmap_1_ce0),
    .ifmap_1_q0(ifmap_1_q0),
    .ifmap_2_address0(ifmap_2_address0),
    .ifmap_2_ce0(ifmap_2_ce0),
    .ifmap_2_q0(ifmap_2_q0),
    .ifmap_3_address0(ifmap_3_address0),
    .ifmap_3_ce0(ifmap_3_ce0),
    .ifmap_3_q0(ifmap_3_q0),
    .ifmap_4_address0(ifmap_4_address0),
    .ifmap_4_ce0(ifmap_4_ce0),
    .ifmap_4_q0(ifmap_4_q0),
    .ifmap_5_address0(ifmap_5_address0),
    .ifmap_5_ce0(ifmap_5_ce0),
    .ifmap_5_q0(ifmap_5_q0),
    .ifmap_6_address0(ifmap_6_address0),
    .ifmap_6_ce0(ifmap_6_ce0),
    .ifmap_6_q0(ifmap_6_q0),
    .ifmap_7_address0(ifmap_7_address0),
    .ifmap_7_ce0(ifmap_7_ce0),
    .ifmap_7_q0(ifmap_7_q0),
    .ifmap_8_address0(ifmap_8_address0),
    .ifmap_8_ce0(ifmap_8_ce0),
    .ifmap_8_q0(ifmap_8_q0),
    .ifmap_9_address0(ifmap_9_address0),
    .ifmap_9_ce0(ifmap_9_ce0),
    .ifmap_9_q0(ifmap_9_q0),
    .result_address0(result_address0),
    .result_ce0(result_ce0),
    .result_we0(result_we0),
    .result_d0(result_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state1)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage9_subdone) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_896)) begin
        if ((1'b1 == ap_condition_1155)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_1_reg_1106 <= ifmap_8_q0;
        end else if ((i_0_reg_1015 == 4'd6)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_1_reg_1106 <= ifmap_6_q0;
        end else if ((i_0_reg_1015 == 4'd4)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_1_reg_1106 <= ifmap_4_q0;
        end else if ((i_0_reg_1015 == 4'd2)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_1_reg_1106 <= ifmap_2_q0;
        end else if ((i_0_reg_1015 == 4'd0)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_1_reg_1106 <= ifmap_0_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_898)) begin
        if ((1'b1 == ap_condition_1155)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_2_reg_1172 <= ifmap_8_q0;
        end else if ((i_0_reg_1015 == 4'd6)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_2_reg_1172 <= ifmap_6_q0;
        end else if ((i_0_reg_1015 == 4'd4)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_2_reg_1172 <= ifmap_4_q0;
        end else if ((i_0_reg_1015 == 4'd2)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_2_reg_1172 <= ifmap_2_q0;
        end else if ((i_0_reg_1015 == 4'd0)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_2_reg_1172 <= ifmap_0_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_902)) begin
        if ((1'b1 == ap_condition_1155)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_3_reg_1238 <= ifmap_8_q0;
        end else if ((i_0_reg_1015 == 4'd6)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_3_reg_1238 <= ifmap_6_q0;
        end else if ((i_0_reg_1015 == 4'd4)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_3_reg_1238 <= ifmap_4_q0;
        end else if ((i_0_reg_1015 == 4'd2)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_3_reg_1238 <= ifmap_2_q0;
        end else if ((i_0_reg_1015 == 4'd0)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_3_reg_1238 <= ifmap_0_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1168)) begin
        if ((1'b1 == ap_condition_1155)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_reg_1055 <= ifmap_8_q0;
        end else if ((i_0_reg_1015 == 4'd6)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_reg_1055 <= ifmap_6_q0;
        end else if ((i_0_reg_1015 == 4'd4)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_reg_1055 <= ifmap_4_q0;
        end else if ((i_0_reg_1015 == 4'd2)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_reg_1055 <= ifmap_2_q0;
        end else if ((i_0_reg_1015 == 4'd0)) begin
            ap_phi_reg_pp0_iter0_phi_ln13_reg_1055 <= ifmap_0_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_896)) begin
        if ((1'b1 == ap_condition_1173)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_1_reg_1141 <= ifmap_9_q0;
        end else if ((or_ln15_reg_2151 == 4'd7)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_1_reg_1141 <= ifmap_7_q0;
        end else if ((or_ln15_reg_2151 == 4'd5)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_1_reg_1141 <= ifmap_5_q0;
        end else if ((or_ln15_reg_2151 == 4'd3)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_1_reg_1141 <= ifmap_3_q0;
        end else if ((or_ln15_reg_2151 == 4'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_1_reg_1141 <= ifmap_1_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_898)) begin
        if ((1'b1 == ap_condition_1173)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_2_reg_1207 <= ifmap_9_q0;
        end else if ((or_ln15_reg_2151 == 4'd7)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_2_reg_1207 <= ifmap_7_q0;
        end else if ((or_ln15_reg_2151 == 4'd5)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_2_reg_1207 <= ifmap_5_q0;
        end else if ((or_ln15_reg_2151 == 4'd3)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_2_reg_1207 <= ifmap_3_q0;
        end else if ((or_ln15_reg_2151 == 4'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_2_reg_1207 <= ifmap_1_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_902)) begin
        if ((1'b1 == ap_condition_1173)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_3_reg_1273 <= ifmap_9_q0;
        end else if ((or_ln15_reg_2151 == 4'd7)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_3_reg_1273 <= ifmap_7_q0;
        end else if ((or_ln15_reg_2151 == 4'd5)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_3_reg_1273 <= ifmap_5_q0;
        end else if ((or_ln15_reg_2151 == 4'd3)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_3_reg_1273 <= ifmap_3_q0;
        end else if ((or_ln15_reg_2151 == 4'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_3_reg_1273 <= ifmap_1_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1168)) begin
        if ((1'b1 == ap_condition_1173)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_reg_1090 <= ifmap_9_q0;
        end else if ((or_ln15_reg_2151 == 4'd7)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_reg_1090 <= ifmap_7_q0;
        end else if ((or_ln15_reg_2151 == 4'd5)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_reg_1090 <= ifmap_5_q0;
        end else if ((or_ln15_reg_2151 == 4'd3)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_reg_1090 <= ifmap_3_q0;
        end else if ((or_ln15_reg_2151 == 4'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln15_reg_1090 <= ifmap_1_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1049)) begin
        if ((1'b1 == ap_condition_1173)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_1_reg_1157 <= ifmap_9_q0;
        end else if ((or_ln15_reg_2151 == 4'd7)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_1_reg_1157 <= ifmap_7_q0;
        end else if ((or_ln15_reg_2151 == 4'd5)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_1_reg_1157 <= ifmap_5_q0;
        end else if ((or_ln15_reg_2151 == 4'd3)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_1_reg_1157 <= ifmap_3_q0;
        end else if ((or_ln15_reg_2151 == 4'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_1_reg_1157 <= ifmap_1_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1057)) begin
        if ((1'b1 == ap_condition_1173)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_2_reg_1223 <= ifmap_9_q0;
        end else if ((or_ln15_reg_2151 == 4'd7)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_2_reg_1223 <= ifmap_7_q0;
        end else if ((or_ln15_reg_2151 == 4'd5)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_2_reg_1223 <= ifmap_5_q0;
        end else if ((or_ln15_reg_2151 == 4'd3)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_2_reg_1223 <= ifmap_3_q0;
        end else if ((or_ln15_reg_2151 == 4'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_2_reg_1223 <= ifmap_1_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1066)) begin
        if ((1'b1 == ap_condition_1173)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_3_reg_1289 <= ifmap_9_q0;
        end else if ((or_ln15_reg_2151 == 4'd7)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_3_reg_1289 <= ifmap_7_q0;
        end else if ((or_ln15_reg_2151 == 4'd5)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_3_reg_1289 <= ifmap_5_q0;
        end else if ((or_ln15_reg_2151 == 4'd3)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_3_reg_1289 <= ifmap_3_q0;
        end else if ((or_ln15_reg_2151 == 4'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_3_reg_1289 <= ifmap_1_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1046)) begin
        if ((1'b1 == ap_condition_1173)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_reg_1040 <= ifmap_9_q0;
        end else if ((or_ln15_reg_2151 == 4'd7)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_reg_1040 <= ifmap_7_q0;
        end else if ((or_ln15_reg_2151 == 4'd5)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_reg_1040 <= ifmap_5_q0;
        end else if ((or_ln15_reg_2151 == 4'd3)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_reg_1040 <= ifmap_3_q0;
        end else if ((or_ln15_reg_2151 == 4'd1)) begin
            ap_phi_reg_pp0_iter0_phi_ln16_reg_1040 <= ifmap_1_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_679)) begin
        if ((1'b1 == ap_condition_438)) begin
            ap_phi_reg_pp0_iter1_phi_ln13_4_reg_1304 <= ifmap_8_q0;
        end else if (((icmp_ln10_reg_2147 == 1'd1) & (i_0_reg_1015 == 4'd6))) begin
            ap_phi_reg_pp0_iter1_phi_ln13_4_reg_1304 <= ifmap_6_q0;
        end else if (((icmp_ln10_reg_2147 == 1'd1) & (i_0_reg_1015 == 4'd4))) begin
            ap_phi_reg_pp0_iter1_phi_ln13_4_reg_1304 <= ifmap_4_q0;
        end else if (((icmp_ln10_reg_2147 == 1'd1) & (i_0_reg_1015 == 4'd2))) begin
            ap_phi_reg_pp0_iter1_phi_ln13_4_reg_1304 <= ifmap_2_q0;
        end else if (((icmp_ln10_reg_2147 == 1'd1) & (i_0_reg_1015 == 4'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln13_4_reg_1304 <= ifmap_0_q0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln13_4_reg_1304 <= ap_phi_reg_pp0_iter0_phi_ln13_4_reg_1304;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_679)) begin
        if ((1'b1 == ap_condition_468)) begin
            ap_phi_reg_pp0_iter1_phi_ln15_4_reg_1339 <= ifmap_9_q0;
        end else if (((or_ln15_reg_2151 == 4'd7) & (icmp_ln10_reg_2147 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln15_4_reg_1339 <= ifmap_7_q0;
        end else if (((or_ln15_reg_2151 == 4'd5) & (icmp_ln10_reg_2147 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln15_4_reg_1339 <= ifmap_5_q0;
        end else if (((or_ln15_reg_2151 == 4'd3) & (icmp_ln10_reg_2147 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln15_4_reg_1339 <= ifmap_3_q0;
        end else if (((or_ln15_reg_2151 == 4'd1) & (icmp_ln10_reg_2147 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_phi_ln15_4_reg_1339 <= ifmap_1_q0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln15_4_reg_1339 <= ap_phi_reg_pp0_iter0_phi_ln15_4_reg_1339;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(or_ln15_reg_2151 == 4'd1) & ~(or_ln15_reg_2151 == 4'd3) & ~(or_ln15_reg_2151 == 4'd5) & ~(or_ln15_reg_2151 == 4'd7) & (icmp_ln10_reg_2147 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_phi_ln16_4_reg_1355 <= ifmap_9_q0;
    end else if (((or_ln15_reg_2151 == 4'd7) & (icmp_ln10_reg_2147 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_phi_ln16_4_reg_1355 <= ifmap_7_q0;
    end else if (((or_ln15_reg_2151 == 4'd5) & (icmp_ln10_reg_2147 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_phi_ln16_4_reg_1355 <= ifmap_5_q0;
    end else if (((or_ln15_reg_2151 == 4'd3) & (icmp_ln10_reg_2147 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_phi_ln16_4_reg_1355 <= ifmap_3_q0;
    end else if (((or_ln15_reg_2151 == 4'd1) & (icmp_ln10_reg_2147 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_phi_ln16_4_reg_1355 <= ifmap_1_q0;
    end else if (((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_phi_reg_pp0_iter1_phi_ln16_4_reg_1355 <= ap_phi_reg_pp0_iter0_phi_ln16_4_reg_1355;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        i_0_reg_1015 <= 4'd0;
    end else if (((icmp_ln10_reg_2147 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_0_reg_1015 <= i_reg_2546;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        idx_0_reg_1027 <= 5'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln10_reg_2147_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        idx_0_reg_1027 <= indvars_iv_reg_1003_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        indvars_iv_reg_1003 <= 5'd5;
    end else if (((icmp_ln10_reg_2147 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvars_iv_reg_1003 <= add_ln10_reg_2551;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        add_ln10_reg_2551 <= add_ln10_fu_1596_p2;
        i_reg_2546 <= i_fu_1590_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        add_ln17_3_reg_2491 <= add_ln17_3_fu_1580_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln17_reg_2162 <= add_ln17_fu_1413_p2;
        zext_ln10_reg_2155[4 : 0] <= zext_ln10_fu_1382_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln10_reg_2147 <= icmp_ln10_fu_1370_p2;
        icmp_ln10_reg_2147_pp0_iter1_reg <= icmp_ln10_reg_2147;
        indvars_iv_reg_1003_pp0_iter1_reg <= indvars_iv_reg_1003;
        select_ln14_4_reg_2556 <= select_ln14_4_fu_1608_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_fu_1370_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_ln15_reg_2151[3 : 1] <= or_ln15_fu_1376_p2[3 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        phi_ln15_1_reg_1141 <= ap_phi_reg_pp0_iter0_phi_ln15_1_reg_1141;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        phi_ln15_2_reg_1207 <= ap_phi_reg_pp0_iter0_phi_ln15_2_reg_1207;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        phi_ln15_3_reg_1273 <= ap_phi_reg_pp0_iter0_phi_ln15_3_reg_1273;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        phi_ln15_4_reg_1339 <= ap_phi_reg_pp0_iter1_phi_ln15_4_reg_1339;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        phi_ln15_reg_1090 <= ap_phi_reg_pp0_iter0_phi_ln15_reg_1090;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        select_ln14_1_reg_2298 <= select_ln14_1_fu_1444_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        select_ln14_2_reg_2379 <= select_ln14_2_fu_1489_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        select_ln14_3_reg_2460 <= select_ln14_3_fu_1540_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        select_ln14_reg_2267 <= select_ln14_fu_1430_p3;
    end
end

always @ (*) begin
    if ((icmp_ln10_fu_1370_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln10_reg_2147 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_i_0_phi_fu_1019_p4 = i_reg_2546;
    end else begin
        ap_phi_mux_i_0_phi_fu_1019_p4 = i_0_reg_1015;
    end
end

always @ (*) begin
    if ((icmp_ln10_reg_2147 == 1'd1)) begin
        if ((1'b1 == ap_condition_1155)) begin
            ap_phi_mux_phi_ln14_1_phi_fu_1124_p10 = ifmap_8_q0;
        end else if ((i_0_reg_1015 == 4'd6)) begin
            ap_phi_mux_phi_ln14_1_phi_fu_1124_p10 = ifmap_6_q0;
        end else if ((i_0_reg_1015 == 4'd4)) begin
            ap_phi_mux_phi_ln14_1_phi_fu_1124_p10 = ifmap_4_q0;
        end else if ((i_0_reg_1015 == 4'd2)) begin
            ap_phi_mux_phi_ln14_1_phi_fu_1124_p10 = ifmap_2_q0;
        end else if ((i_0_reg_1015 == 4'd0)) begin
            ap_phi_mux_phi_ln14_1_phi_fu_1124_p10 = ifmap_0_q0;
        end else begin
            ap_phi_mux_phi_ln14_1_phi_fu_1124_p10 = ap_phi_reg_pp0_iter0_phi_ln14_1_reg_1121;
        end
    end else begin
        ap_phi_mux_phi_ln14_1_phi_fu_1124_p10 = ap_phi_reg_pp0_iter0_phi_ln14_1_reg_1121;
    end
end

always @ (*) begin
    if ((icmp_ln10_reg_2147 == 1'd1)) begin
        if ((1'b1 == ap_condition_1155)) begin
            ap_phi_mux_phi_ln14_2_phi_fu_1190_p10 = ifmap_8_q0;
        end else if ((i_0_reg_1015 == 4'd6)) begin
            ap_phi_mux_phi_ln14_2_phi_fu_1190_p10 = ifmap_6_q0;
        end else if ((i_0_reg_1015 == 4'd4)) begin
            ap_phi_mux_phi_ln14_2_phi_fu_1190_p10 = ifmap_4_q0;
        end else if ((i_0_reg_1015 == 4'd2)) begin
            ap_phi_mux_phi_ln14_2_phi_fu_1190_p10 = ifmap_2_q0;
        end else if ((i_0_reg_1015 == 4'd0)) begin
            ap_phi_mux_phi_ln14_2_phi_fu_1190_p10 = ifmap_0_q0;
        end else begin
            ap_phi_mux_phi_ln14_2_phi_fu_1190_p10 = ap_phi_reg_pp0_iter0_phi_ln14_2_reg_1187;
        end
    end else begin
        ap_phi_mux_phi_ln14_2_phi_fu_1190_p10 = ap_phi_reg_pp0_iter0_phi_ln14_2_reg_1187;
    end
end

always @ (*) begin
    if ((icmp_ln10_reg_2147 == 1'd1)) begin
        if ((1'b1 == ap_condition_1155)) begin
            ap_phi_mux_phi_ln14_3_phi_fu_1256_p10 = ifmap_8_q0;
        end else if ((i_0_reg_1015 == 4'd6)) begin
            ap_phi_mux_phi_ln14_3_phi_fu_1256_p10 = ifmap_6_q0;
        end else if ((i_0_reg_1015 == 4'd4)) begin
            ap_phi_mux_phi_ln14_3_phi_fu_1256_p10 = ifmap_4_q0;
        end else if ((i_0_reg_1015 == 4'd2)) begin
            ap_phi_mux_phi_ln14_3_phi_fu_1256_p10 = ifmap_2_q0;
        end else if ((i_0_reg_1015 == 4'd0)) begin
            ap_phi_mux_phi_ln14_3_phi_fu_1256_p10 = ifmap_0_q0;
        end else begin
            ap_phi_mux_phi_ln14_3_phi_fu_1256_p10 = ap_phi_reg_pp0_iter0_phi_ln14_3_reg_1253;
        end
    end else begin
        ap_phi_mux_phi_ln14_3_phi_fu_1256_p10 = ap_phi_reg_pp0_iter0_phi_ln14_3_reg_1253;
    end
end

always @ (*) begin
    if ((icmp_ln10_reg_2147 == 1'd1)) begin
        if ((1'b1 == ap_condition_1155)) begin
            ap_phi_mux_phi_ln14_4_phi_fu_1322_p10 = ifmap_8_q0;
        end else if ((i_0_reg_1015 == 4'd6)) begin
            ap_phi_mux_phi_ln14_4_phi_fu_1322_p10 = ifmap_6_q0;
        end else if ((i_0_reg_1015 == 4'd4)) begin
            ap_phi_mux_phi_ln14_4_phi_fu_1322_p10 = ifmap_4_q0;
        end else if ((i_0_reg_1015 == 4'd2)) begin
            ap_phi_mux_phi_ln14_4_phi_fu_1322_p10 = ifmap_2_q0;
        end else if ((i_0_reg_1015 == 4'd0)) begin
            ap_phi_mux_phi_ln14_4_phi_fu_1322_p10 = ifmap_0_q0;
        end else begin
            ap_phi_mux_phi_ln14_4_phi_fu_1322_p10 = ap_phi_reg_pp0_iter1_phi_ln14_4_reg_1319;
        end
    end else begin
        ap_phi_mux_phi_ln14_4_phi_fu_1322_p10 = ap_phi_reg_pp0_iter1_phi_ln14_4_reg_1319;
    end
end

always @ (*) begin
    if ((icmp_ln10_reg_2147 == 1'd1)) begin
        if ((1'b1 == ap_condition_1155)) begin
            ap_phi_mux_phi_ln14_phi_fu_1073_p10 = ifmap_8_q0;
        end else if ((i_0_reg_1015 == 4'd6)) begin
            ap_phi_mux_phi_ln14_phi_fu_1073_p10 = ifmap_6_q0;
        end else if ((i_0_reg_1015 == 4'd4)) begin
            ap_phi_mux_phi_ln14_phi_fu_1073_p10 = ifmap_4_q0;
        end else if ((i_0_reg_1015 == 4'd2)) begin
            ap_phi_mux_phi_ln14_phi_fu_1073_p10 = ifmap_2_q0;
        end else if ((i_0_reg_1015 == 4'd0)) begin
            ap_phi_mux_phi_ln14_phi_fu_1073_p10 = ifmap_0_q0;
        end else begin
            ap_phi_mux_phi_ln14_phi_fu_1073_p10 = ap_phi_reg_pp0_iter0_phi_ln14_reg_1070;
        end
    end else begin
        ap_phi_mux_phi_ln14_phi_fu_1073_p10 = ap_phi_reg_pp0_iter0_phi_ln14_reg_1070;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ifmap_0_address0 = 64'd9;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            ifmap_0_address0 = 64'd8;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ifmap_0_address0 = 64'd7;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ifmap_0_address0 = 64'd6;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ifmap_0_address0 = 64'd5;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ifmap_0_address0 = 64'd4;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ifmap_0_address0 = 64'd2;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ifmap_0_address0 = 64'd1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ifmap_0_address0 = 64'd3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ifmap_0_address0 = 64'd0;
        end else begin
            ifmap_0_address0 = 'bx;
        end
    end else begin
        ifmap_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ifmap_0_ce0 = 1'b1;
    end else begin
        ifmap_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ifmap_1_address0 = 64'd9;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            ifmap_1_address0 = 64'd8;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ifmap_1_address0 = 64'd7;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ifmap_1_address0 = 64'd6;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ifmap_1_address0 = 64'd5;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ifmap_1_address0 = 64'd4;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ifmap_1_address0 = 64'd2;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ifmap_1_address0 = 64'd1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ifmap_1_address0 = 64'd3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ifmap_1_address0 = 64'd0;
        end else begin
            ifmap_1_address0 = 'bx;
        end
    end else begin
        ifmap_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ifmap_1_ce0 = 1'b1;
    end else begin
        ifmap_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ifmap_2_address0 = 64'd9;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            ifmap_2_address0 = 64'd8;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ifmap_2_address0 = 64'd7;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ifmap_2_address0 = 64'd6;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ifmap_2_address0 = 64'd5;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ifmap_2_address0 = 64'd4;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ifmap_2_address0 = 64'd2;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ifmap_2_address0 = 64'd1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ifmap_2_address0 = 64'd3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ifmap_2_address0 = 64'd0;
        end else begin
            ifmap_2_address0 = 'bx;
        end
    end else begin
        ifmap_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ifmap_2_ce0 = 1'b1;
    end else begin
        ifmap_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ifmap_3_address0 = 64'd9;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            ifmap_3_address0 = 64'd8;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ifmap_3_address0 = 64'd7;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ifmap_3_address0 = 64'd6;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ifmap_3_address0 = 64'd5;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ifmap_3_address0 = 64'd4;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ifmap_3_address0 = 64'd2;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ifmap_3_address0 = 64'd1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ifmap_3_address0 = 64'd3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ifmap_3_address0 = 64'd0;
        end else begin
            ifmap_3_address0 = 'bx;
        end
    end else begin
        ifmap_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ifmap_3_ce0 = 1'b1;
    end else begin
        ifmap_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ifmap_4_address0 = 64'd9;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            ifmap_4_address0 = 64'd8;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ifmap_4_address0 = 64'd7;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ifmap_4_address0 = 64'd6;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ifmap_4_address0 = 64'd5;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ifmap_4_address0 = 64'd4;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ifmap_4_address0 = 64'd2;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ifmap_4_address0 = 64'd1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ifmap_4_address0 = 64'd3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ifmap_4_address0 = 64'd0;
        end else begin
            ifmap_4_address0 = 'bx;
        end
    end else begin
        ifmap_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ifmap_4_ce0 = 1'b1;
    end else begin
        ifmap_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ifmap_5_address0 = 64'd9;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            ifmap_5_address0 = 64'd8;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ifmap_5_address0 = 64'd7;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ifmap_5_address0 = 64'd6;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ifmap_5_address0 = 64'd5;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ifmap_5_address0 = 64'd4;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ifmap_5_address0 = 64'd2;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ifmap_5_address0 = 64'd1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ifmap_5_address0 = 64'd3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ifmap_5_address0 = 64'd0;
        end else begin
            ifmap_5_address0 = 'bx;
        end
    end else begin
        ifmap_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ifmap_5_ce0 = 1'b1;
    end else begin
        ifmap_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ifmap_6_address0 = 64'd9;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            ifmap_6_address0 = 64'd8;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ifmap_6_address0 = 64'd7;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ifmap_6_address0 = 64'd6;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ifmap_6_address0 = 64'd5;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ifmap_6_address0 = 64'd4;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ifmap_6_address0 = 64'd2;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ifmap_6_address0 = 64'd1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ifmap_6_address0 = 64'd3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ifmap_6_address0 = 64'd0;
        end else begin
            ifmap_6_address0 = 'bx;
        end
    end else begin
        ifmap_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ifmap_6_ce0 = 1'b1;
    end else begin
        ifmap_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ifmap_7_address0 = 64'd9;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            ifmap_7_address0 = 64'd8;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ifmap_7_address0 = 64'd7;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ifmap_7_address0 = 64'd6;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ifmap_7_address0 = 64'd5;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ifmap_7_address0 = 64'd4;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ifmap_7_address0 = 64'd2;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ifmap_7_address0 = 64'd1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ifmap_7_address0 = 64'd3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ifmap_7_address0 = 64'd0;
        end else begin
            ifmap_7_address0 = 'bx;
        end
    end else begin
        ifmap_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ifmap_7_ce0 = 1'b1;
    end else begin
        ifmap_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ifmap_8_address0 = 64'd9;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            ifmap_8_address0 = 64'd8;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ifmap_8_address0 = 64'd7;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ifmap_8_address0 = 64'd6;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ifmap_8_address0 = 64'd5;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ifmap_8_address0 = 64'd4;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ifmap_8_address0 = 64'd2;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ifmap_8_address0 = 64'd1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ifmap_8_address0 = 64'd3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ifmap_8_address0 = 64'd0;
        end else begin
            ifmap_8_address0 = 'bx;
        end
    end else begin
        ifmap_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ifmap_8_ce0 = 1'b1;
    end else begin
        ifmap_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            ifmap_9_address0 = 64'd9;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            ifmap_9_address0 = 64'd8;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ifmap_9_address0 = 64'd7;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ifmap_9_address0 = 64'd6;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ifmap_9_address0 = 64'd5;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ifmap_9_address0 = 64'd4;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ifmap_9_address0 = 64'd2;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ifmap_9_address0 = 64'd1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ifmap_9_address0 = 64'd3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ifmap_9_address0 = 64'd0;
        end else begin
            ifmap_9_address0 = 'bx;
        end
    end else begin
        ifmap_9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ifmap_9_ce0 = 1'b1;
    end else begin
        ifmap_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        result_address0 = zext_ln17_4_fu_1643_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        result_address0 = zext_ln17_3_fu_1585_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        result_address0 = zext_ln17_2_fu_1529_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        result_address0 = zext_ln17_1_fu_1479_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        result_address0 = zext_ln17_fu_1419_p1;
    end else begin
        result_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        result_ce0 = 1'b1;
    end else begin
        result_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        result_d0 = select_ln16_4_fu_1634_p3;
    end else if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        result_d0 = select_ln16_3_fu_1571_p3;
    end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        result_d0 = select_ln16_2_fu_1520_p3;
    end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        result_d0 = select_ln16_1_fu_1470_p3;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        result_d0 = select_ln16_fu_1404_p3;
    end else begin
        result_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln10_reg_2147_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage9_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln10_reg_2147 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        result_we0 = 1'b1;
    end else begin
        result_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln10_fu_1370_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln10_fu_1370_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_fu_1596_p2 = (indvars_iv_reg_1003 + 5'd5);

assign add_ln17_1_fu_1497_p2 = (zext_ln10_reg_2155 + 6'd2);

assign add_ln17_2_fu_1548_p2 = (zext_ln10_reg_2155 + 6'd3);

assign add_ln17_3_fu_1580_p2 = (zext_ln10_reg_2155 + 6'd4);

assign add_ln17_fu_1413_p2 = (idx_0_reg_1027 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage9_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1046 = ((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_1049 = ((1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_1057 = ((1'b0 == ap_block_pp0_stage6_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_1066 = ((1'b0 == ap_block_pp0_stage8_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_1155 = (~(i_0_reg_1015 == 4'd0) & ~(i_0_reg_1015 == 4'd2) & ~(i_0_reg_1015 == 4'd4) & ~(i_0_reg_1015 == 4'd6));
end

always @ (*) begin
    ap_condition_1168 = ((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_1173 = (~(or_ln15_reg_2151 == 4'd1) & ~(or_ln15_reg_2151 == 4'd3) & ~(or_ln15_reg_2151 == 4'd5) & ~(or_ln15_reg_2151 == 4'd7));
end

always @ (*) begin
    ap_condition_438 = (~(i_0_reg_1015 == 4'd0) & ~(i_0_reg_1015 == 4'd2) & ~(i_0_reg_1015 == 4'd4) & ~(i_0_reg_1015 == 4'd6) & (icmp_ln10_reg_2147 == 1'd1));
end

always @ (*) begin
    ap_condition_468 = (~(or_ln15_reg_2151 == 4'd1) & ~(or_ln15_reg_2151 == 4'd3) & ~(or_ln15_reg_2151 == 4'd5) & ~(or_ln15_reg_2151 == 4'd7) & (icmp_ln10_reg_2147 == 1'd1));
end

always @ (*) begin
    ap_condition_679 = ((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_896 = ((1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln10_reg_2147 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

always @ (*) begin
    ap_condition_898 = ((1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_902 = ((1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln10_reg_2147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_phi_ln13_4_reg_1304 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln14_1_reg_1121 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln14_2_reg_1187 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln14_3_reg_1253 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln14_reg_1070 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln15_4_reg_1339 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln16_4_reg_1355 = 'bx;

assign ap_phi_reg_pp0_iter1_phi_ln14_4_reg_1319 = 'bx;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign i_fu_1590_p2 = (i_0_reg_1015 + 4'd2);

assign icmp_ln10_fu_1370_p2 = ((ap_phi_mux_i_0_phi_fu_1019_p4 < 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln14_1_fu_1438_p2 = (($signed(ap_phi_reg_pp0_iter0_phi_ln13_1_reg_1106) < $signed(ap_phi_mux_phi_ln14_1_phi_fu_1124_p10)) ? 1'b1 : 1'b0);

assign icmp_ln14_2_fu_1483_p2 = (($signed(ap_phi_reg_pp0_iter0_phi_ln13_2_reg_1172) < $signed(ap_phi_mux_phi_ln14_2_phi_fu_1190_p10)) ? 1'b1 : 1'b0);

assign icmp_ln14_3_fu_1534_p2 = (($signed(ap_phi_reg_pp0_iter0_phi_ln13_3_reg_1238) < $signed(ap_phi_mux_phi_ln14_3_phi_fu_1256_p10)) ? 1'b1 : 1'b0);

assign icmp_ln14_4_fu_1602_p2 = (($signed(ap_phi_reg_pp0_iter1_phi_ln13_4_reg_1304) < $signed(ap_phi_mux_phi_ln14_4_phi_fu_1322_p10)) ? 1'b1 : 1'b0);

assign icmp_ln14_fu_1424_p2 = (($signed(ap_phi_reg_pp0_iter0_phi_ln13_reg_1055) < $signed(ap_phi_mux_phi_ln14_phi_fu_1073_p10)) ? 1'b1 : 1'b0);

assign icmp_ln15_1_fu_1452_p2 = (($signed(select_ln14_1_reg_2298) < $signed(phi_ln15_1_reg_1141)) ? 1'b1 : 1'b0);

assign icmp_ln15_2_fu_1502_p2 = (($signed(select_ln14_2_reg_2379) < $signed(phi_ln15_2_reg_1207)) ? 1'b1 : 1'b0);

assign icmp_ln15_3_fu_1553_p2 = (($signed(select_ln14_3_reg_2460) < $signed(phi_ln15_3_reg_1273)) ? 1'b1 : 1'b0);

assign icmp_ln15_4_fu_1616_p2 = (($signed(select_ln14_4_reg_2556) < $signed(phi_ln15_4_reg_1339)) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_1386_p2 = (($signed(select_ln14_reg_2267) < $signed(phi_ln15_reg_1090)) ? 1'b1 : 1'b0);

assign icmp_ln16_1_fu_1464_p2 = (($signed(select_ln15_1_fu_1457_p3) < $signed(ap_phi_reg_pp0_iter0_phi_ln16_1_reg_1157)) ? 1'b1 : 1'b0);

assign icmp_ln16_2_fu_1514_p2 = (($signed(select_ln15_2_fu_1507_p3) < $signed(ap_phi_reg_pp0_iter0_phi_ln16_2_reg_1223)) ? 1'b1 : 1'b0);

assign icmp_ln16_3_fu_1565_p2 = (($signed(select_ln15_3_fu_1558_p3) < $signed(ap_phi_reg_pp0_iter0_phi_ln16_3_reg_1289)) ? 1'b1 : 1'b0);

assign icmp_ln16_4_fu_1628_p2 = (($signed(select_ln15_4_fu_1621_p3) < $signed(ap_phi_reg_pp0_iter1_phi_ln16_4_reg_1355)) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_1398_p2 = (($signed(select_ln15_fu_1391_p3) < $signed(ap_phi_reg_pp0_iter0_phi_ln16_reg_1040)) ? 1'b1 : 1'b0);

assign or_ln15_fu_1376_p2 = (ap_phi_mux_i_0_phi_fu_1019_p4 | 4'd1);

assign select_ln14_1_fu_1444_p3 = ((icmp_ln14_1_fu_1438_p2[0:0] === 1'b1) ? ap_phi_mux_phi_ln14_1_phi_fu_1124_p10 : ap_phi_reg_pp0_iter0_phi_ln13_1_reg_1106);

assign select_ln14_2_fu_1489_p3 = ((icmp_ln14_2_fu_1483_p2[0:0] === 1'b1) ? ap_phi_mux_phi_ln14_2_phi_fu_1190_p10 : ap_phi_reg_pp0_iter0_phi_ln13_2_reg_1172);

assign select_ln14_3_fu_1540_p3 = ((icmp_ln14_3_fu_1534_p2[0:0] === 1'b1) ? ap_phi_mux_phi_ln14_3_phi_fu_1256_p10 : ap_phi_reg_pp0_iter0_phi_ln13_3_reg_1238);

assign select_ln14_4_fu_1608_p3 = ((icmp_ln14_4_fu_1602_p2[0:0] === 1'b1) ? ap_phi_mux_phi_ln14_4_phi_fu_1322_p10 : ap_phi_reg_pp0_iter1_phi_ln13_4_reg_1304);

assign select_ln14_fu_1430_p3 = ((icmp_ln14_fu_1424_p2[0:0] === 1'b1) ? ap_phi_mux_phi_ln14_phi_fu_1073_p10 : ap_phi_reg_pp0_iter0_phi_ln13_reg_1055);

assign select_ln15_1_fu_1457_p3 = ((icmp_ln15_1_fu_1452_p2[0:0] === 1'b1) ? phi_ln15_1_reg_1141 : select_ln14_1_reg_2298);

assign select_ln15_2_fu_1507_p3 = ((icmp_ln15_2_fu_1502_p2[0:0] === 1'b1) ? phi_ln15_2_reg_1207 : select_ln14_2_reg_2379);

assign select_ln15_3_fu_1558_p3 = ((icmp_ln15_3_fu_1553_p2[0:0] === 1'b1) ? phi_ln15_3_reg_1273 : select_ln14_3_reg_2460);

assign select_ln15_4_fu_1621_p3 = ((icmp_ln15_4_fu_1616_p2[0:0] === 1'b1) ? phi_ln15_4_reg_1339 : select_ln14_4_reg_2556);

assign select_ln15_fu_1391_p3 = ((icmp_ln15_fu_1386_p2[0:0] === 1'b1) ? phi_ln15_reg_1090 : select_ln14_reg_2267);

assign select_ln16_1_fu_1470_p3 = ((icmp_ln16_1_fu_1464_p2[0:0] === 1'b1) ? ap_phi_reg_pp0_iter0_phi_ln16_1_reg_1157 : select_ln15_1_fu_1457_p3);

assign select_ln16_2_fu_1520_p3 = ((icmp_ln16_2_fu_1514_p2[0:0] === 1'b1) ? ap_phi_reg_pp0_iter0_phi_ln16_2_reg_1223 : select_ln15_2_fu_1507_p3);

assign select_ln16_3_fu_1571_p3 = ((icmp_ln16_3_fu_1565_p2[0:0] === 1'b1) ? ap_phi_reg_pp0_iter0_phi_ln16_3_reg_1289 : select_ln15_3_fu_1558_p3);

assign select_ln16_4_fu_1634_p3 = ((icmp_ln16_4_fu_1628_p2[0:0] === 1'b1) ? ap_phi_reg_pp0_iter1_phi_ln16_4_reg_1355 : select_ln15_4_fu_1621_p3);

assign select_ln16_fu_1404_p3 = ((icmp_ln16_fu_1398_p2[0:0] === 1'b1) ? ap_phi_reg_pp0_iter0_phi_ln16_reg_1040 : select_ln15_fu_1391_p3);

assign zext_ln10_fu_1382_p1 = idx_0_reg_1027;

assign zext_ln17_1_fu_1479_p1 = add_ln17_reg_2162;

assign zext_ln17_2_fu_1529_p1 = add_ln17_1_fu_1497_p2;

assign zext_ln17_3_fu_1585_p1 = add_ln17_2_fu_1548_p2;

assign zext_ln17_4_fu_1643_p1 = add_ln17_3_reg_2491;

assign zext_ln17_fu_1419_p1 = idx_0_reg_1027;

always @ (posedge ap_clk) begin
    or_ln15_reg_2151[0] <= 1'b1;
    zext_ln10_reg_2155[5] <= 1'b0;
end

endmodule //Max_Pooling_10x10
