// ==============================================================
// Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC v2019.2 (64-bit)
// Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
// ==============================================================
#ifndef XCONV_H
#define XCONV_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xconv_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XConv_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XConv;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XConv_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XConv_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XConv_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XConv_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XConv_Initialize(XConv *InstancePtr, u16 DeviceId);
XConv_Config* XConv_LookupConfig(u16 DeviceId);
int XConv_CfgInitialize(XConv *InstancePtr, XConv_Config *ConfigPtr);
#else
int XConv_Initialize(XConv *InstancePtr, const char* InstanceName);
int XConv_Release(XConv *InstancePtr);
#endif


void XConv_Set_ifmap_0(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_0(XConv *InstancePtr);
void XConv_Set_ifmap_1(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_1(XConv *InstancePtr);
void XConv_Set_ifmap_2(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_2(XConv *InstancePtr);
void XConv_Set_ifmap_3(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_3(XConv *InstancePtr);
void XConv_Set_ifmap_4(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_4(XConv *InstancePtr);
void XConv_Set_ifmap_5(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_5(XConv *InstancePtr);
void XConv_Set_ifmap_6(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_6(XConv *InstancePtr);
void XConv_Set_ifmap_7(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_7(XConv *InstancePtr);
void XConv_Set_ifmap_8(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_8(XConv *InstancePtr);
void XConv_Set_ifmap_9(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_9(XConv *InstancePtr);
void XConv_Set_ifmap_10(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_10(XConv *InstancePtr);
void XConv_Set_ifmap_11(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_11(XConv *InstancePtr);
void XConv_Set_ifmap_12(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_12(XConv *InstancePtr);
void XConv_Set_ifmap_13(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_13(XConv *InstancePtr);
void XConv_Set_ifmap_14(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_14(XConv *InstancePtr);
void XConv_Set_ifmap_15(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_15(XConv *InstancePtr);
void XConv_Set_ifmap_16(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_16(XConv *InstancePtr);
void XConv_Set_ifmap_17(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_17(XConv *InstancePtr);
void XConv_Set_ifmap_18(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_18(XConv *InstancePtr);
void XConv_Set_ifmap_19(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_19(XConv *InstancePtr);
void XConv_Set_ifmap_20(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_20(XConv *InstancePtr);
void XConv_Set_ifmap_21(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_21(XConv *InstancePtr);
void XConv_Set_ifmap_22(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_22(XConv *InstancePtr);
void XConv_Set_ifmap_23(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_23(XConv *InstancePtr);
void XConv_Set_ifmap_24(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_24(XConv *InstancePtr);
void XConv_Set_ifmap_25(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_25(XConv *InstancePtr);
void XConv_Set_ifmap_26(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_26(XConv *InstancePtr);
void XConv_Set_ifmap_27(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_27(XConv *InstancePtr);
void XConv_Set_ifmap_28(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_28(XConv *InstancePtr);
void XConv_Set_ifmap_29(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_29(XConv *InstancePtr);
void XConv_Set_ifmap_30(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_30(XConv *InstancePtr);
void XConv_Set_ifmap_31(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_31(XConv *InstancePtr);
void XConv_Set_ifmap_32(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_32(XConv *InstancePtr);
void XConv_Set_ifmap_33(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_33(XConv *InstancePtr);
void XConv_Set_ifmap_34(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_34(XConv *InstancePtr);
void XConv_Set_ifmap_35(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_35(XConv *InstancePtr);
void XConv_Set_ifmap_36(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_36(XConv *InstancePtr);
void XConv_Set_ifmap_37(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_37(XConv *InstancePtr);
void XConv_Set_ifmap_38(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_38(XConv *InstancePtr);
void XConv_Set_ifmap_39(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_39(XConv *InstancePtr);
void XConv_Set_ifmap_40(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_40(XConv *InstancePtr);
void XConv_Set_ifmap_41(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_41(XConv *InstancePtr);
void XConv_Set_ifmap_42(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_42(XConv *InstancePtr);
void XConv_Set_ifmap_43(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_43(XConv *InstancePtr);
void XConv_Set_ifmap_44(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_44(XConv *InstancePtr);
void XConv_Set_ifmap_45(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_45(XConv *InstancePtr);
void XConv_Set_ifmap_46(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_46(XConv *InstancePtr);
void XConv_Set_ifmap_47(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_47(XConv *InstancePtr);
void XConv_Set_ifmap_48(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_48(XConv *InstancePtr);
void XConv_Set_ifmap_49(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_49(XConv *InstancePtr);
void XConv_Set_ifmap_50(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_50(XConv *InstancePtr);
void XConv_Set_ifmap_51(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_51(XConv *InstancePtr);
void XConv_Set_ifmap_52(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_52(XConv *InstancePtr);
void XConv_Set_ifmap_53(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_53(XConv *InstancePtr);
void XConv_Set_ifmap_54(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_54(XConv *InstancePtr);
void XConv_Set_ifmap_55(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_55(XConv *InstancePtr);
void XConv_Set_ifmap_56(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_56(XConv *InstancePtr);
void XConv_Set_ifmap_57(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_57(XConv *InstancePtr);
void XConv_Set_ifmap_58(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_58(XConv *InstancePtr);
void XConv_Set_ifmap_59(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_59(XConv *InstancePtr);
void XConv_Set_ifmap_60(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_60(XConv *InstancePtr);
void XConv_Set_ifmap_61(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_61(XConv *InstancePtr);
void XConv_Set_ifmap_62(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_62(XConv *InstancePtr);
void XConv_Set_ifmap_63(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_63(XConv *InstancePtr);
void XConv_Set_ifmap_64(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_64(XConv *InstancePtr);
void XConv_Set_ifmap_65(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_65(XConv *InstancePtr);
void XConv_Set_ifmap_66(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_66(XConv *InstancePtr);
void XConv_Set_ifmap_67(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_67(XConv *InstancePtr);
void XConv_Set_ifmap_68(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_68(XConv *InstancePtr);
void XConv_Set_ifmap_69(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_69(XConv *InstancePtr);
void XConv_Set_ifmap_70(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_70(XConv *InstancePtr);
void XConv_Set_ifmap_71(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_71(XConv *InstancePtr);
void XConv_Set_ifmap_72(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_72(XConv *InstancePtr);
void XConv_Set_ifmap_73(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_73(XConv *InstancePtr);
void XConv_Set_ifmap_74(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_74(XConv *InstancePtr);
void XConv_Set_ifmap_75(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_75(XConv *InstancePtr);
void XConv_Set_ifmap_76(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_76(XConv *InstancePtr);
void XConv_Set_ifmap_77(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_77(XConv *InstancePtr);
void XConv_Set_ifmap_78(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_78(XConv *InstancePtr);
void XConv_Set_ifmap_79(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_79(XConv *InstancePtr);
void XConv_Set_ifmap_80(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_80(XConv *InstancePtr);
void XConv_Set_ifmap_81(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_81(XConv *InstancePtr);
void XConv_Set_ifmap_82(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_82(XConv *InstancePtr);
void XConv_Set_ifmap_83(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_83(XConv *InstancePtr);
void XConv_Set_ifmap_84(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_84(XConv *InstancePtr);
void XConv_Set_ifmap_85(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_85(XConv *InstancePtr);
void XConv_Set_ifmap_86(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_86(XConv *InstancePtr);
void XConv_Set_ifmap_87(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_87(XConv *InstancePtr);
void XConv_Set_ifmap_88(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_88(XConv *InstancePtr);
void XConv_Set_ifmap_89(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_89(XConv *InstancePtr);
void XConv_Set_ifmap_90(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_90(XConv *InstancePtr);
void XConv_Set_ifmap_91(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_91(XConv *InstancePtr);
void XConv_Set_ifmap_92(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_92(XConv *InstancePtr);
void XConv_Set_ifmap_93(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_93(XConv *InstancePtr);
void XConv_Set_ifmap_94(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_94(XConv *InstancePtr);
void XConv_Set_ifmap_95(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_95(XConv *InstancePtr);
void XConv_Set_ifmap_96(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_96(XConv *InstancePtr);
void XConv_Set_ifmap_97(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_97(XConv *InstancePtr);
void XConv_Set_ifmap_98(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_98(XConv *InstancePtr);
void XConv_Set_ifmap_99(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_99(XConv *InstancePtr);
void XConv_Set_ifmap_100(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_100(XConv *InstancePtr);
void XConv_Set_ifmap_101(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_101(XConv *InstancePtr);
void XConv_Set_ifmap_102(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_102(XConv *InstancePtr);
void XConv_Set_ifmap_103(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_103(XConv *InstancePtr);
void XConv_Set_ifmap_104(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_104(XConv *InstancePtr);
void XConv_Set_ifmap_105(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_105(XConv *InstancePtr);
void XConv_Set_ifmap_106(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_106(XConv *InstancePtr);
void XConv_Set_ifmap_107(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_107(XConv *InstancePtr);
void XConv_Set_ifmap_108(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_108(XConv *InstancePtr);
void XConv_Set_ifmap_109(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_109(XConv *InstancePtr);
void XConv_Set_ifmap_110(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_110(XConv *InstancePtr);
void XConv_Set_ifmap_111(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_111(XConv *InstancePtr);
void XConv_Set_ifmap_112(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_112(XConv *InstancePtr);
void XConv_Set_ifmap_113(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_113(XConv *InstancePtr);
void XConv_Set_ifmap_114(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_114(XConv *InstancePtr);
void XConv_Set_ifmap_115(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_115(XConv *InstancePtr);
void XConv_Set_ifmap_116(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_116(XConv *InstancePtr);
void XConv_Set_ifmap_117(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_117(XConv *InstancePtr);
void XConv_Set_ifmap_118(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_118(XConv *InstancePtr);
void XConv_Set_ifmap_119(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_119(XConv *InstancePtr);
void XConv_Set_ifmap_120(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_120(XConv *InstancePtr);
void XConv_Set_ifmap_121(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_121(XConv *InstancePtr);
void XConv_Set_ifmap_122(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_122(XConv *InstancePtr);
void XConv_Set_ifmap_123(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_123(XConv *InstancePtr);
void XConv_Set_ifmap_124(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_124(XConv *InstancePtr);
void XConv_Set_ifmap_125(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_125(XConv *InstancePtr);
void XConv_Set_ifmap_126(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_126(XConv *InstancePtr);
void XConv_Set_ifmap_127(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_127(XConv *InstancePtr);
void XConv_Set_ifmap_128(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_128(XConv *InstancePtr);
void XConv_Set_ifmap_129(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_129(XConv *InstancePtr);
void XConv_Set_ifmap_130(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_130(XConv *InstancePtr);
void XConv_Set_ifmap_131(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_131(XConv *InstancePtr);
void XConv_Set_ifmap_132(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_132(XConv *InstancePtr);
void XConv_Set_ifmap_133(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_133(XConv *InstancePtr);
void XConv_Set_ifmap_134(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_134(XConv *InstancePtr);
void XConv_Set_ifmap_135(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_135(XConv *InstancePtr);
void XConv_Set_ifmap_136(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_136(XConv *InstancePtr);
void XConv_Set_ifmap_137(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_137(XConv *InstancePtr);
void XConv_Set_ifmap_138(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_138(XConv *InstancePtr);
void XConv_Set_ifmap_139(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_139(XConv *InstancePtr);
void XConv_Set_ifmap_140(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_140(XConv *InstancePtr);
void XConv_Set_ifmap_141(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_141(XConv *InstancePtr);
void XConv_Set_ifmap_142(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_142(XConv *InstancePtr);
void XConv_Set_ifmap_143(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_143(XConv *InstancePtr);
void XConv_Set_ifmap_144(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_144(XConv *InstancePtr);
void XConv_Set_ifmap_145(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_145(XConv *InstancePtr);
void XConv_Set_ifmap_146(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_146(XConv *InstancePtr);
void XConv_Set_ifmap_147(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_147(XConv *InstancePtr);
void XConv_Set_ifmap_148(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_148(XConv *InstancePtr);
void XConv_Set_ifmap_149(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_149(XConv *InstancePtr);
void XConv_Set_ifmap_150(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_150(XConv *InstancePtr);
void XConv_Set_ifmap_151(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_151(XConv *InstancePtr);
void XConv_Set_ifmap_152(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_152(XConv *InstancePtr);
void XConv_Set_ifmap_153(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_153(XConv *InstancePtr);
void XConv_Set_ifmap_154(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_154(XConv *InstancePtr);
void XConv_Set_ifmap_155(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_155(XConv *InstancePtr);
void XConv_Set_ifmap_156(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_156(XConv *InstancePtr);
void XConv_Set_ifmap_157(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_157(XConv *InstancePtr);
void XConv_Set_ifmap_158(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_158(XConv *InstancePtr);
void XConv_Set_ifmap_159(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_159(XConv *InstancePtr);
void XConv_Set_ifmap_160(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_160(XConv *InstancePtr);
void XConv_Set_ifmap_161(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_161(XConv *InstancePtr);
void XConv_Set_ifmap_162(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_162(XConv *InstancePtr);
void XConv_Set_ifmap_163(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_163(XConv *InstancePtr);
void XConv_Set_ifmap_164(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_164(XConv *InstancePtr);
void XConv_Set_ifmap_165(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_165(XConv *InstancePtr);
void XConv_Set_ifmap_166(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_166(XConv *InstancePtr);
void XConv_Set_ifmap_167(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_167(XConv *InstancePtr);
void XConv_Set_ifmap_168(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_168(XConv *InstancePtr);
void XConv_Set_ifmap_169(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_169(XConv *InstancePtr);
void XConv_Set_ifmap_170(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_170(XConv *InstancePtr);
void XConv_Set_ifmap_171(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_171(XConv *InstancePtr);
void XConv_Set_ifmap_172(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_172(XConv *InstancePtr);
void XConv_Set_ifmap_173(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_173(XConv *InstancePtr);
void XConv_Set_ifmap_174(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_174(XConv *InstancePtr);
void XConv_Set_ifmap_175(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_175(XConv *InstancePtr);
void XConv_Set_ifmap_176(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_176(XConv *InstancePtr);
void XConv_Set_ifmap_177(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_177(XConv *InstancePtr);
void XConv_Set_ifmap_178(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_178(XConv *InstancePtr);
void XConv_Set_ifmap_179(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_179(XConv *InstancePtr);
void XConv_Set_ifmap_180(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_180(XConv *InstancePtr);
void XConv_Set_ifmap_181(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_181(XConv *InstancePtr);
void XConv_Set_ifmap_182(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_182(XConv *InstancePtr);
void XConv_Set_ifmap_183(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_183(XConv *InstancePtr);
void XConv_Set_ifmap_184(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_184(XConv *InstancePtr);
void XConv_Set_ifmap_185(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_185(XConv *InstancePtr);
void XConv_Set_ifmap_186(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_186(XConv *InstancePtr);
void XConv_Set_ifmap_187(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_187(XConv *InstancePtr);
void XConv_Set_ifmap_188(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_188(XConv *InstancePtr);
void XConv_Set_ifmap_189(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_189(XConv *InstancePtr);
void XConv_Set_ifmap_190(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_190(XConv *InstancePtr);
void XConv_Set_ifmap_191(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_191(XConv *InstancePtr);
void XConv_Set_ifmap_192(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_192(XConv *InstancePtr);
void XConv_Set_ifmap_193(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_193(XConv *InstancePtr);
void XConv_Set_ifmap_194(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_194(XConv *InstancePtr);
void XConv_Set_ifmap_195(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_195(XConv *InstancePtr);
void XConv_Set_ifmap_196(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_196(XConv *InstancePtr);
void XConv_Set_ifmap_197(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_197(XConv *InstancePtr);
void XConv_Set_ifmap_198(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_198(XConv *InstancePtr);
void XConv_Set_ifmap_199(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_199(XConv *InstancePtr);
void XConv_Set_ifmap_200(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_200(XConv *InstancePtr);
void XConv_Set_ifmap_201(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_201(XConv *InstancePtr);
void XConv_Set_ifmap_202(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_202(XConv *InstancePtr);
void XConv_Set_ifmap_203(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_203(XConv *InstancePtr);
void XConv_Set_ifmap_204(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_204(XConv *InstancePtr);
void XConv_Set_ifmap_205(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_205(XConv *InstancePtr);
void XConv_Set_ifmap_206(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_206(XConv *InstancePtr);
void XConv_Set_ifmap_207(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_207(XConv *InstancePtr);
void XConv_Set_ifmap_208(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_208(XConv *InstancePtr);
void XConv_Set_ifmap_209(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_209(XConv *InstancePtr);
void XConv_Set_ifmap_210(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_210(XConv *InstancePtr);
void XConv_Set_ifmap_211(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_211(XConv *InstancePtr);
void XConv_Set_ifmap_212(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_212(XConv *InstancePtr);
void XConv_Set_ifmap_213(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_213(XConv *InstancePtr);
void XConv_Set_ifmap_214(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_214(XConv *InstancePtr);
void XConv_Set_ifmap_215(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_215(XConv *InstancePtr);
void XConv_Set_ifmap_216(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_216(XConv *InstancePtr);
void XConv_Set_ifmap_217(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_217(XConv *InstancePtr);
void XConv_Set_ifmap_218(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_218(XConv *InstancePtr);
void XConv_Set_ifmap_219(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_219(XConv *InstancePtr);
void XConv_Set_ifmap_220(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_220(XConv *InstancePtr);
void XConv_Set_ifmap_221(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_221(XConv *InstancePtr);
void XConv_Set_ifmap_222(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_222(XConv *InstancePtr);
void XConv_Set_ifmap_223(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_223(XConv *InstancePtr);
void XConv_Set_ifmap_224(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_224(XConv *InstancePtr);
void XConv_Set_ifmap_225(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_225(XConv *InstancePtr);
void XConv_Set_ifmap_226(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_226(XConv *InstancePtr);
void XConv_Set_ifmap_227(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_227(XConv *InstancePtr);
void XConv_Set_ifmap_228(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_228(XConv *InstancePtr);
void XConv_Set_ifmap_229(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_229(XConv *InstancePtr);
void XConv_Set_ifmap_230(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_230(XConv *InstancePtr);
void XConv_Set_ifmap_231(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_231(XConv *InstancePtr);
void XConv_Set_ifmap_232(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_232(XConv *InstancePtr);
void XConv_Set_ifmap_233(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_233(XConv *InstancePtr);
void XConv_Set_ifmap_234(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_234(XConv *InstancePtr);
void XConv_Set_ifmap_235(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_235(XConv *InstancePtr);
void XConv_Set_ifmap_236(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_236(XConv *InstancePtr);
void XConv_Set_ifmap_237(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_237(XConv *InstancePtr);
void XConv_Set_ifmap_238(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_238(XConv *InstancePtr);
void XConv_Set_ifmap_239(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_239(XConv *InstancePtr);
void XConv_Set_ifmap_240(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_240(XConv *InstancePtr);
void XConv_Set_ifmap_241(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_241(XConv *InstancePtr);
void XConv_Set_ifmap_242(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_242(XConv *InstancePtr);
void XConv_Set_ifmap_243(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_243(XConv *InstancePtr);
void XConv_Set_ifmap_244(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_244(XConv *InstancePtr);
void XConv_Set_ifmap_245(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_245(XConv *InstancePtr);
void XConv_Set_ifmap_246(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_246(XConv *InstancePtr);
void XConv_Set_ifmap_247(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_247(XConv *InstancePtr);
void XConv_Set_ifmap_248(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_248(XConv *InstancePtr);
void XConv_Set_ifmap_249(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_249(XConv *InstancePtr);
void XConv_Set_ifmap_250(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_250(XConv *InstancePtr);
void XConv_Set_ifmap_251(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_251(XConv *InstancePtr);
void XConv_Set_ifmap_252(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_252(XConv *InstancePtr);
void XConv_Set_ifmap_253(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_253(XConv *InstancePtr);
void XConv_Set_ifmap_254(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_254(XConv *InstancePtr);
void XConv_Set_ifmap_255(XConv *InstancePtr, u32 Data);
u32 XConv_Get_ifmap_255(XConv *InstancePtr);
void XConv_Set_filter_0(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_0(XConv *InstancePtr);
void XConv_Set_filter_1(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_1(XConv *InstancePtr);
void XConv_Set_filter_2(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_2(XConv *InstancePtr);
void XConv_Set_filter_3(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_3(XConv *InstancePtr);
void XConv_Set_filter_4(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_4(XConv *InstancePtr);
void XConv_Set_filter_5(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_5(XConv *InstancePtr);
void XConv_Set_filter_6(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_6(XConv *InstancePtr);
void XConv_Set_filter_7(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_7(XConv *InstancePtr);
void XConv_Set_filter_8(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_8(XConv *InstancePtr);
void XConv_Set_filter_9(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_9(XConv *InstancePtr);
void XConv_Set_filter_10(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_10(XConv *InstancePtr);
void XConv_Set_filter_11(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_11(XConv *InstancePtr);
void XConv_Set_filter_12(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_12(XConv *InstancePtr);
void XConv_Set_filter_13(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_13(XConv *InstancePtr);
void XConv_Set_filter_14(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_14(XConv *InstancePtr);
void XConv_Set_filter_15(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_15(XConv *InstancePtr);
void XConv_Set_filter_16(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_16(XConv *InstancePtr);
void XConv_Set_filter_17(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_17(XConv *InstancePtr);
void XConv_Set_filter_18(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_18(XConv *InstancePtr);
void XConv_Set_filter_19(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_19(XConv *InstancePtr);
void XConv_Set_filter_20(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_20(XConv *InstancePtr);
void XConv_Set_filter_21(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_21(XConv *InstancePtr);
void XConv_Set_filter_22(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_22(XConv *InstancePtr);
void XConv_Set_filter_23(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_23(XConv *InstancePtr);
void XConv_Set_filter_24(XConv *InstancePtr, u32 Data);
u32 XConv_Get_filter_24(XConv *InstancePtr);
u32 XConv_Get_ofmap_0_BaseAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_0_HighAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_0_TotalBytes(XConv *InstancePtr);
u32 XConv_Get_ofmap_0_BitWidth(XConv *InstancePtr);
u32 XConv_Get_ofmap_0_Depth(XConv *InstancePtr);
u32 XConv_Write_ofmap_0_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Read_ofmap_0_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Write_ofmap_0_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Read_ofmap_0_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Get_ofmap_1_BaseAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_1_HighAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_1_TotalBytes(XConv *InstancePtr);
u32 XConv_Get_ofmap_1_BitWidth(XConv *InstancePtr);
u32 XConv_Get_ofmap_1_Depth(XConv *InstancePtr);
u32 XConv_Write_ofmap_1_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Read_ofmap_1_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Write_ofmap_1_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Read_ofmap_1_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Get_ofmap_2_BaseAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_2_HighAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_2_TotalBytes(XConv *InstancePtr);
u32 XConv_Get_ofmap_2_BitWidth(XConv *InstancePtr);
u32 XConv_Get_ofmap_2_Depth(XConv *InstancePtr);
u32 XConv_Write_ofmap_2_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Read_ofmap_2_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Write_ofmap_2_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Read_ofmap_2_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Get_ofmap_3_BaseAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_3_HighAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_3_TotalBytes(XConv *InstancePtr);
u32 XConv_Get_ofmap_3_BitWidth(XConv *InstancePtr);
u32 XConv_Get_ofmap_3_Depth(XConv *InstancePtr);
u32 XConv_Write_ofmap_3_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Read_ofmap_3_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Write_ofmap_3_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Read_ofmap_3_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Get_ofmap_4_BaseAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_4_HighAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_4_TotalBytes(XConv *InstancePtr);
u32 XConv_Get_ofmap_4_BitWidth(XConv *InstancePtr);
u32 XConv_Get_ofmap_4_Depth(XConv *InstancePtr);
u32 XConv_Write_ofmap_4_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Read_ofmap_4_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Write_ofmap_4_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Read_ofmap_4_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Get_ofmap_5_BaseAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_5_HighAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_5_TotalBytes(XConv *InstancePtr);
u32 XConv_Get_ofmap_5_BitWidth(XConv *InstancePtr);
u32 XConv_Get_ofmap_5_Depth(XConv *InstancePtr);
u32 XConv_Write_ofmap_5_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Read_ofmap_5_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Write_ofmap_5_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Read_ofmap_5_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Get_ofmap_6_BaseAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_6_HighAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_6_TotalBytes(XConv *InstancePtr);
u32 XConv_Get_ofmap_6_BitWidth(XConv *InstancePtr);
u32 XConv_Get_ofmap_6_Depth(XConv *InstancePtr);
u32 XConv_Write_ofmap_6_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Read_ofmap_6_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Write_ofmap_6_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Read_ofmap_6_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Get_ofmap_7_BaseAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_7_HighAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_7_TotalBytes(XConv *InstancePtr);
u32 XConv_Get_ofmap_7_BitWidth(XConv *InstancePtr);
u32 XConv_Get_ofmap_7_Depth(XConv *InstancePtr);
u32 XConv_Write_ofmap_7_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Read_ofmap_7_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Write_ofmap_7_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Read_ofmap_7_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Get_ofmap_8_BaseAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_8_HighAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_8_TotalBytes(XConv *InstancePtr);
u32 XConv_Get_ofmap_8_BitWidth(XConv *InstancePtr);
u32 XConv_Get_ofmap_8_Depth(XConv *InstancePtr);
u32 XConv_Write_ofmap_8_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Read_ofmap_8_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Write_ofmap_8_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Read_ofmap_8_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Get_ofmap_9_BaseAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_9_HighAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_9_TotalBytes(XConv *InstancePtr);
u32 XConv_Get_ofmap_9_BitWidth(XConv *InstancePtr);
u32 XConv_Get_ofmap_9_Depth(XConv *InstancePtr);
u32 XConv_Write_ofmap_9_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Read_ofmap_9_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Write_ofmap_9_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Read_ofmap_9_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Get_ofmap_10_BaseAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_10_HighAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_10_TotalBytes(XConv *InstancePtr);
u32 XConv_Get_ofmap_10_BitWidth(XConv *InstancePtr);
u32 XConv_Get_ofmap_10_Depth(XConv *InstancePtr);
u32 XConv_Write_ofmap_10_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Read_ofmap_10_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Write_ofmap_10_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Read_ofmap_10_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Get_ofmap_11_BaseAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_11_HighAddress(XConv *InstancePtr);
u32 XConv_Get_ofmap_11_TotalBytes(XConv *InstancePtr);
u32 XConv_Get_ofmap_11_BitWidth(XConv *InstancePtr);
u32 XConv_Get_ofmap_11_Depth(XConv *InstancePtr);
u32 XConv_Write_ofmap_11_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Read_ofmap_11_Words(XConv *InstancePtr, int offset, int *data, int length);
u32 XConv_Write_ofmap_11_Bytes(XConv *InstancePtr, int offset, char *data, int length);
u32 XConv_Read_ofmap_11_Bytes(XConv *InstancePtr, int offset, char *data, int length);

#ifdef __cplusplus
}
#endif

#endif
